moc_globe_atl implementation
NCAR/geocat-temp pull request #22
Opened 2020-11-05 04:43 UTC by anissa111

Addresses #9 

Purpose: implements moc_globe_atl function in geocat f2py efforts

Summary of changes:
- moves MOC.loops.f into 
- creates .pyf file for f2py conversion
- creates wrapper function
- includes and alters previously created tests for moc_globe_atl

2020-11-10 19:59 UTC, erogluorhan requested changes
It looks great overall!

Please update from `master` branch to get the latest version of `build.sh` and `meta.yaml` files. Then add your corresponding `moc_globe_atl` line to `build.sh`.

2020-11-10 20:38 UTC, anissa111 commented
> Please update from `master` branch to get the latest version of `build.sh` and `meta.yaml` files. Then add your corresponding `moc_globe_atl` line to `build.sh`.

Addressed, thank you for the catch!

2020-11-10 22:25 UTC, erogluorhan approved these changes
It looks great and I am approving it. Just out of curiosity: It looks like test cases `test_moc_globe_atl_msg_nan_float32` and `test_moc_globe_atl_msg_99_float32` have been dropped; were they abundant in the existence of `test_moc_globe_atl_msg_nan` and `test_moc_globe_atl_msg_99?

2020-11-11 17:44 UTC, pilotchute commented on src/geocat/temp/__init__.py
> +from .moc_globe_atl_wrapper import moc_globe_atl
I'm going to add parentheses on master once merged

2020-11-11 17:45 UTC, pilotchute approved these changes

2020-11-11 17:45 UTC, merged